#ifndef INDEX_HTML_H
#define INDEX_HTML_H

static const char INDEX_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>PromoBeacon | Proximity Marketing Redefined</title>\n"
"    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&display=swap\" rel=\"stylesheet\">\n"
"    <style>\n"
"        :root {\n"
"            --primary: #4f46e5;\n"
"            --primary-glow: rgba(79, 70, 229, 0.4);\n"
"            --bg: #0f172a;\n"
"            --card-bg: rgba(30, 41, 59, 0.7);\n"
"            --text-main: #f8fafc;\n"
"            --text-dim: #94a3b8;\n"
"        }\n"
"\n"
"        * {\n"
"            box-sizing: border-box;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"        }\n"
"\n"
"        body {\n"
"            font-family: 'Outfit', sans-serif;\n"
"            background-color: var(--bg);\n"
"            background-image: \n"
"                radial-gradient(circle at 0% 0%, rgba(79, 70, 229, 0.15) 0, transparent 50%),\n"
"                radial-gradient(circle at 100% 100%, rgba(124, 58, 237, 0.1) 0, transparent 50%);\n"
"            color: var(--text-main);\n"
"            line-height: 1.6;\n"
"            min-height: 100vh;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            overflow-x: hidden;\n"
"        }\n"
"\n"
"        .container {\n"
"            max-width: 800px;\n"
"            margin: 0 auto;\n"
"            padding: 40px 20px;\n"
"            flex: 1;\n"
"        }\n"
"\n"
"        header {\n"
"            text-align: center;\n"
"            margin-bottom: 60px;\n"
"            animation: fadeInDown 0.8s ease-out;\n"
"        }\n"
"\n"
"        .logo-text {\n"
"            font-size: 14px;\n"
"            font-weight: 600;\n"
"            letter-spacing: 4px;\n"
"            color: var(--primary);\n"
"            text-transform: uppercase;\n"
"            margin-bottom: 12px;\n"
"        }\n"
"\n"
"        h1 {\n"
"            font-size: 3rem;\n"
"            font-weight: 600;\n"
"            line-height: 1.1;\n"
"            background: linear-gradient(to right, #fff, #94a3b8);\n"
"            -webkit-background-clip: text;\n"
"            -webkit-text-fill-color: transparent;\n"
"            margin-bottom: 24px;\n"
"        }\n"
"\n"
"        .hero-desc {\n"
"            font-size: 1.25rem;\n"
"            color: var(--text-dim);\n"
"            max-width: 600px;\n"
"            margin: 0 auto;\n"
"        }\n"
"\n"
"        .features-grid {\n"
"            display: grid;\n"
"            grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));\n"
"            gap: 20px;\n"
"            margin-bottom: 60px;\n"
"            animation: fadeInUp 1s ease-out 0.2s both;\n"
"        }\n"
"\n"
"        .feature-card {\n"
"            background: var(--card-bg);\n"
"            backdrop-filter: blur(12px);\n"
"            border: 1px solid rgba(255, 255, 255, 0.1);\n"
"            padding: 32px;\n"
"            border-radius: 24px;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"\n"
"        .feature-card:hover {\n"
"            transform: translateY(-5px);\n"
"            border-color: var(--primary);\n"
"            box-shadow: 0 10px 30px -10px var(--primary-glow);\n"
"        }\n"
"\n"
"        .feature-icon {\n"
"            width: 48px;\n"
"            height: 48px;\n"
"            background: rgba(79, 70, 229, 0.1);\n"
"            border-radius: 12px;\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            margin-bottom: 20px;\n"
"            color: var(--primary);\n"
"        }\n"
"\n"
"        h3 {\n"
"            font-size: 1.25rem;\n"
"            margin-bottom: 12px;\n"
"        }\n"
"\n"
"        p {\n"
"            color: var(--text-dim);\n"
"            font-size: 0.95rem;\n"
"        }\n"
"\n"
"        .cta-section {\n"
"            text-align: center;\n"
"            padding: 40px;\n"
"            background: radial-gradient(circle at center, rgba(79, 70, 229, 0.2) 0%, transparent 70%);\n"
"            border-radius: 32px;\n"
"            animation: fadeIn 1.2s ease-out 0.4s both;\n"
"        }\n"
"\n"
"        .btn {\n"
"            display: inline-block;\n"
"            background: var(--primary);\n"
"            color: white;\n"
"            padding: 16px 40px;\n"
"            border-radius: 14px;\n"
"            font-weight: 600;\n"
"            text-decoration: none;\n"
"            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"            box-shadow: 0 4px 20px var(--primary-glow);\n"
"            margin-top: 20px;\n"
"        }\n"
"\n"
"        .btn:hover {\n"
"            transform: scale(1.05);\n"
"            box-shadow: 0 8px 30px var(--primary-glow);\n"
"        }\n"
"\n"
"        footer {\n"
"            text-align: center;\n"
"            padding: 40px;\n"
"            font-size: 0.85rem;\n"
"            color: var(--text-dim);\n"
"            border-top: 1px solid rgba(255, 255, 255, 0.05);\n"
"        }\n"
"\n"
"        @keyframes fadeInDown {\n"
"            from { opacity: 0; transform: translateY(-20px); }\n"
"            to { opacity: 1; transform: translateY(0); }\n"
"        }\n"
"\n"
"        @keyframes fadeInUp {\n"
"            from { opacity: 0; transform: translateY(20px); }\n"
"            to { opacity: 1; transform: translateY(0); }\n"
"        }\n"
"\n"
"        @keyframes fadeIn {\n"
"            from { opacity: 0; }\n"
"            to { opacity: 1; }\n"
"        }\n"
"\n"
"        @media (max-width: 640px) {\n"
"            h1 { font-size: 2.25rem; }\n"
"            .container { padding: 20px; }\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <header>\n"
"            <div class=\"logo-text\">PROMOBEACON</div>\n"
"            <h1>The Future of <br>Proximity Marketing</h1>\n"
"            <p class=\"hero-desc\">Smart advertising that connects your brand directly with nearby customers via Bluetooth and Wi-Fi.</p>\n"
"        </header>\n"
"\n"
"        <div class=\"features-grid\">\n"
"            <div class=\"feature-card\">\n"
"                <div class=\"feature-icon\">📡</div>\n"
"                <h3>Plug & Play</h3>\n"
"                <p>Standalone infrastructure. No internet or cloud required to start reaching local audiences.</p>\n"
"            </div>\n"
"            <div class=\"feature-card\">\n"
"                <div class=\"feature-icon\">✨</div>\n"
"                <h3>Auto-Popup</h3>\n"
"                <p>Automatically triggers a beautiful captive portal on customer smartphones upon connection.</p>\n"
"            </div>\n"
"            <div class=\"feature-card\">\n"
"                <div class=\"feature-icon\">⚡</div>\n"
"                <h3>Hyper Local</h3>\n"
"                <p>Deliver the right message at the right time. Perfect for events, stores, and smart cities.</p>\n"
"            </div>\n"
"        </div>\n"
"\n"
"        <div class=\"cta-section\">\n"
"            <h2>Ready to evolve?</h2>\n"
"            <p>Explore all the possibilities of our hardware solutions.</p>\n"
"            <a href=\"http://www.promobeacon.com\" class=\"btn\">Explore Official Website</a>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <footer>\n"
"        &copy; 2026 PromoBeacon Tech. Advanced Proximity Solutions.\n"
"    </footer>\n"
"</body>\n"
"</html>\n"
"";

#endif
